version: '3.3'
services:
        web:
                build:
                        context: .
                        dockerfile: Dockerfile.dev
                ports: 
                        - "5000:8881"
                volumes:
                        - /app/node_modules
                        - .:/app
                stdin_open: true
        tests:
                build:
                        context: .
                        dockerfile: Dockerfile.dev
                volumes:
                        - /app/node_modules
                        - .:/app
                command: ["npm", "run", "test"]

                

